import { PrismaClient, Role, Permission, DayOfWeek } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Starting database seeding...');

  // 1. Create Admin User
  const admin = await prisma.user.upsert({
    where: { email: 'admin@djadwal.com' },
    update: {},
    create: {
      email: 'admin@djadwal.com',
      name: 'System Admin',
      password: 'admin_password_hash', // Should be hashed in real app
      role: Role.ADMIN,
      permission: Permission.ADMIN,
    },
  });
  console.log('✅ Admin user created/verified');

  // 2. Create Current Academic Year
  const currentYear = await prisma.academicYear.upsert({
    where: { name: '2024-2025' },
    update: {},
    create: {
      name: '2024-2025',
      startDate: new Date('2024-09-01'),
      endDate: new Date('2025-07-15'),
      isCurrent: true,
    },
  });
  console.log('✅ Academic year created');

  // 3. Create Semesters
  await prisma.semester.upsert({
    where: { id: '00000000-0000-0000-0000-000000000001' },
    update: {},
    create: {
      id: '00000000-0000-0000-0000-000000000001',
      name: 'S1',
      startDate: new Date('2024-09-01'),
      endDate: new Date('2025-01-30'),
      isCurrent: true,
      academicYearId: currentYear.id,
    },
  });

  await prisma.semester.upsert({
    where: { id: '00000000-0000-0000-0000-000000000002' },
    update: {},
    create: {
      id: '00000000-0000-0000-0000-000000000002',
      name: 'S2',
      startDate: new Date('2025-02-01'),
      endDate: new Date('2025-07-15'),
      isCurrent: false,
      academicYearId: currentYear.id,
    },
  });
  console.log('✅ Semesters created');

  // 4. Create default Print Settings
  await prisma.printSettings.create({
    data: {
      universityName: 'University Name',
      facultyName: 'Faculty Name',
      headerNotes: 'Academic Schedule',
      footerNotes: 'Generated by Djadwal V2',
    },
  });
  console.log('✅ Default print settings created');

  console.log('✨ Seeding completed successfully!');
}

main()
  .catch((e) => {
    console.error('❌ Seeding failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
